### PR TITLE
updated package name to reflect the project name instead of the scope…

### PR DESCRIPTION
**Pull request by nicholas-b-carter**
#2 - Updated the package name in package.json to reflect a non-scoped project. This allowed me to register the project on npm. The updated package reflects these changes.

### CODE REVIEW

**Comment by walkerrandolphsmith** [comment]
@nicholas-b-carter thanks!

**Comment by walkerrandolphsmith** [comment]
@nicholas-b-carter I notice you published to npm with the new name. The module on npm is no longer scoped. Do you have any idea why the scoped package was receiving a 404. Also I am not able to publish updates the the non-scoped package given I didn't publish it. Do you know how to add me as a contributor to the package on npmorg?

**Comment by nicholas-b-carter** [comment]
@walkerrandolphsmith, yes the reason the package was 404ing was because of the permissions of the package. An example of this is https://github.com/rlidwka/sinopia/issues/278#issuecomment-176731408

**Comment by nicholas-b-carter** [comment]
(As of 2015-04-19, the public npm registry does support scoped packages)

**Comment by nicholas-b-carter** [comment]
https://docs.npmjs.com/misc/scope#publishing-scoped-packages

**Comment by walkerrandolphsmith** [comment]
Thanks seems like this is the key:
> To publish a public scoped package, you must specify --access public with the initial publication. This will publish the package and set access to public as if you had run npm access public after publishing.

Thanks for the help @nicholas-b-carter .

**Pull request merged**
